import { Word } from '../model/types';

export const words: Array<Word> = [
	{
		id: 1,
		slug: 'word1',
		created: '2022-01-01',
		modified: '2022-01-01',
		translations_count: 1,
		favorite: false,
		types: ['type1', 'type2'],
		text: 'textWord1',
		language: 'en',
		activity: 'ACTIVE',
		translations: [
			{
				text: 'textTranslation1',
			},
		],
		collections: [1],
	},
	{
		id: 2,
		slug: 'word2',
		created: '2022-01-01',
		modified: '2022-01-01',
		translations_count: 1,
		favorite: false,
		types: ['type1', 'type2'],
		text: 'textWord2',
		language: 'en',
		activity: 'ACTIVE',
		translations: [
			{
				text: 'textTranslation2',
			},
		],
		collections: [2],
	},
	{
		id: 3,
		slug: 'word3',
		created: '2022-01-01',
		modified: '2022-01-01',
		translations_count: 2,
		favorite: false,
		types: ['type1', 'type2'],
		text: 'textWord3',
		language: 'en',
		activity: 'ACTIVE',
		translations: [
			{
				text: 'textTranslation3',
			},
			{
				text: 'textTranslation32',
			},
		],
		collections: [1],
	},
	{
		id: 4,
		slug: 'word4',
		created: '2022-01-01',
		modified: '2022-01-01',
		translations_count: 1,
		favorite: false,
		types: ['type1', 'type2'],
		text: 'textWord4',
		language: 'en',
		activity: 'INACTIVE',
		translations: [
			{
				text: 'textTranslation4',
			},
		],
		collections: [3],
	},
	{
		id: 5,
		slug: 'word5',
		created: '2022-01-01',
		modified: '2022-01-01',
		translations_count: 1,
		favorite: false,
		types: ['type1', 'type2'],
		text: 'textWord5',
		language: 'en',
		activity: 'INACTIVE',
		translations: [
			{
				text: 'textTranslation5',
			},
		],
		collections: [3],
	},
	{
		id: 6,
		slug: 'word6',
		created: '2022-01-01',
		modified: '2022-01-01',
		translations_count: 1,
		favorite: false,
		types: ['type1', 'type2'],
		text: 'textWord6',
		language: 'en',
		activity: 'ACTIVE',
		translations: [
			{
				text: 'textTranslation6',
			},
		],
		collections: [2],
	},
	{
		id: 7,
		slug: 'word7',
		created: '2022-01-01',
		modified: '2022-01-01',
		translations_count: 2,
		favorite: false,
		types: ['type1', 'type2'],
		text: 'textWord7',
		language: 'en',
		activity: 'MASTERED',
		translations: [
			{
				text: 'textTranslation7',
			},
			{
				text: 'textTranslation72',
			},
		],
		collections: [2, 3],
	},
	{
		id: 8,
		slug: 'word8',
		created: '2022-01-01',
		modified: '2022-01-01',
		translations_count: 1,
		favorite: false,
		types: ['type1', 'type2'],
		text: 'textWord8',
		activity: 'MASTERED',
		language: 'en',
		translations: [
			{
				text: 'textTranslation8',
			},
		],
		collections: [1, 2],
	},
	{
		id: 9,
		slug: 'word9',
		created: '2022-01-01',
		modified: '2022-01-01',
		translations_count: 1,
		favorite: false,
		types: ['type1', 'type2'],
		text: 'textWord9',
		activity: 'MASTERED',
		language: 'en',
		translations: [
			{
				text: 'textTranslation9',
			},
		],
		collections: [1],
	},
	{
		id: 10,
		slug: 'word10',
		created: '2022-01-01',
		modified: '2022-01-01',
		translations_count: 2,
		favorite: false,
		types: ['type1', 'type2'],
		text: 'textWord10',
		activity: 'MASTERED',
		language: 'en',
		translations: [
			{
				text: 'textTranslation10',
			},
			{
				text: 'textTranslation102',
			},
		],
		collections: [2],
	},
	{
		id: 11,
		slug: 'word11',
		created: '2022-01-01',
		modified: '2022-01-01',
		translations_count: 1,
		favorite: false,
		types: ['type1', 'type2'],
		text: 'textWord11',
		language: 'en',
		activity: 'MASTERED',
		translations: [
			{
				text: 'textTranslation11',
			},
		],
		collections: [3],
	},
	{
		id: 12,
		slug: 'word12',
		created: '2022-01-01',
		modified: '2022-01-01',
		translations_count: 1,
		favorite: false,
		types: ['type1', 'type2'],
		text: 'textWord12',
		language: 'en',
		activity: 'MASTERED',
		translations: [
			{
				text: 'textTranslation12',
			},
		],
		collections: [3],
	},
	{
		id: 13,
		slug: 'word13',
		created: '2022-01-01',
		modified: '2022-01-01',
		translations_count: 1,
		favorite: false,
		types: ['type1', 'type2'],
		text: 'textWord13',
		language: 'en',
		activity: 'ACTIVE',
		translations: [
			{
				text: 'textTranslation13',
			},
		],
		collections: [1, 3],
	},
	{
		id: 14,
		slug: 'word14',
		created: '2022-01-01',
		modified: '2022-01-01',
		translations_count: 1,
		favorite: false,
		types: ['type1', 'type2'],
		text: 'textWord14',
		language: 'en',
		activity: 'MASTERED',
		translations: [
			{
				text: 'textTranslation14',
			},
		],
		collections: [2, 3],
	},
	{
		id: 15,
		slug: 'word15',
		created: '2022-01-01',
		modified: '2022-01-01',
		translations_count: 2,
		favorite: false,
		types: ['type1', 'type2'],
		text: 'textWord15',
		language: 'en',
		activity: 'ACTIVE',
		translations: [
			{
				text: 'textTranslation15',
			},
			{
				text: 'textTranslation152',
			},
		],
		collections: [2],
	},
];
